apiVersion: batch/v1
kind: Job
metadata:
  name: lris-mark4
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - args:
        - cd PypeIt; git fetch; git checkout lris_red_new; git pull --ff-only; cd
          pypeit/data/telluric/atm_grids; aws --endpoint http://rook-ceph-rgw-nautiluss3.rook
          s3 cp s3://pypeit/telluric/atm_grids/TelFit_MaunaKea_3100_26100_R20000.fits
          TelFit_MaunaKea_3100_26100_R20000.fits --force; aws --endpoint http://rook-ceph-rgw-nautiluss3.rook
          s3 cp s3://pypeit/telluric/atm_grids/TelFit_LasCampanas_3100_26100_R20000.fits
          TelFit_LasCampanas_3100_26100_R20000.fits --force; cd /; cd PypeIt-development-suite;
          git fetch; git checkout new_lris_red_dev; git pull --ff-only; mkdir CALIBS;
          aws --endpoint http://rook-ceph-rgw-nautiluss3.rook s3 cp s3://pypeit/CALIBS
          CALIBS/ --recursive --force; mkdir RAW_DATA; aws --endpoint http://rook-ceph-rgw-nautiluss3.rook
          s3 cp s3://pypeit/RAW_DATA RAW_DATA/ --recursive --force; ./pypeit_test
          -q -t 6 develop -r pypeit.report -o /tmp/REDUX_OUT; aws --endpoint http://rook-ceph-rgw-nautiluss3.rook
          s3 cp pypeit.report s3://pypeit/Reports/lris-mark4.report;
        command:
        - /bin/bash
        - -c
        env:
        - name: PYPEIT_DEV
          value: /PypeIt-development-suite
        - name: ENDPOINT_URL
          value: http://rook-ceph-rgw-nautiluss3.rook
        - name: S3_ENDPOINT
          value: rook-ceph-rgw-nautiluss3.rook
        image: localhost:30081/profxj/pypeit:latest
        imagePullPolicy: Always
        name: container
        resources:
          limits:
            cpu: '7'
            ephemeral-storage: 300Gi
            memory: 100Gi
          requests:
            cpu: '6'
            ephemeral-storage: 250Gi
            memory: 50Gi
        volumeMounts:
        - mountPath: /root/.aws/credentials
          name: prp-s3-credentials
          subPath: credentials
        - mountPath: /tmp
          name: ephemeral
        - mountPath: /dev/shm
          name: dshm
      nodeSelector:
        gpu-type: 1080Ti
        nautilus.io/disktype: nvme
      restartPolicy: Never
      volumes:
      - name: prp-s3-credentials
        secret:
          secretName: prp-s3-credentials
      - emptyDir:
          medium: Memory
        name: dshm
      - emptyDir: {}
        name: ephemeral
